version: '3.9'

services:
  deepstream:
    build:
      context: .
      dockerfile: ./docker_image/Dockerfile
    image: deepstream_app:experimental
    container_name: deepstream_app
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - DEEPSTREAM_DISABLE_BOX_SEGMENTATION=1  # Disable bounding box segmentation
      - DEEPSTREAM_IGNORE_CLASS_IDS_SEGMENTATION=0,4 # you can specify class IDs to ignore here in list example: 0,4
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/deepstream_app
    working_dir: /deepstream_app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    stdin_open: true
    tty: true
    ports:
      - "8554:8554"  # Example RTSP
      - "5000:5000"  # Example HTTP inference API
      - "8888:8888"  # Example Jupyter or UI
